# Generated by Django 6.1 on 2026-08-08 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('movie', 'Movie'), ('tv', 'TV Series'), ('anime', 'Anime')], default='movie', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('date_watched', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('watching', 'Watching'), ('planned', 'Plan to watch'), ('dropped', 'Dropped')], default='completed', max_length=15)),
                ('ep_current', models.IntegerField(blank=True, null=True)),
                ('ep_total', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_watched', '-created_at'],
            },
        ),
    ]
